### ISSUE TITLE
sign in issue

### ISSUE THREAD

**Issue by Brucej93** [matkatmusic/ChordieApp_IssueTracker#38]
After entering my license and purchase email. nothing happens. it tries to do something, then just says to enter again in red letters.

**Comment by matkatmusic** [comment]
I noticed a lot of people are not entering their credentials exactly as they appeared when they checked out.  the fields are case-sensitive.  A lot of people are adding a capitalized first letter, or their entire email is capitalized, or they're not even entering in the email they used for purchase.  they're entering in some other email, or they're adding blank spaces because they copied more of the page that their license key is on than they realized.   Or, and this was the weirdest one, they entered their license key from their purchase of Chordie from a few years ago). 

This is not a bug.  You need to enter the correct credentials. It's expecting you to use the email **exactly** as you entered it when you went through checkout along with the license key on your receipt.

**Comment by Brucej93** [comment]
Ah. Thank you for the reply!
