### ISSUE TITLE
Issues with Virtual Keyboard on Windows

### ISSUE THREAD

**Issue by frauber84** [matkatmusic/ChordieApp_IssueTracker#8]
So far I'm testing without a MIDI input, just to trigger bugs and exceptions and I have noticed some strange behaviours with the virtual keyboard.

1) It doesn't works until I click on any piano key.
2) While it does light up the keys, it doesn't affect the notation display.
3) To be really useful, you could think of adopting this two-octave setup (as in some DAWs), this way Chordie could be used even when there isn't a MIDI input available.

```
 2 3   5 6 7
Q W E R T Y U  (upper octave)

 S D   G H J
Z X C V B N M (lower octave)
```

**Comment by matkatmusic** [comment]
1) the keyboard isn't the focused component, when you click on it, it becomes focused.
2) it never did this in previous builds because the keyboard never "latched".  I have that implemented here: https://youtu.be/WbosKb3bBEA https://youtu.be/yBbtQyOTMTg
3) if more people request this, I'll look into it.
